us_regions = [
    {
        "region": "Northeast",
        "states": [
            "Connecticut",
            "Maine",
            "Massachusetts",
            "New Hampshire",
            "Rhode Island",
            "Vermont",
            "New Jersey",
            "New York",
            "Pennsylvania",
        ],
    },
    {
        "region": "South",
        "states": [
            "Delaware",
            "Florida",
            "Georgia",
            "Maryland",
            "North Carolina",
            "South Carolina",
            "Virginia",
            "West Virginia",
            "Alabama",
            "Kentucky",
            "Mississippi",
            "Tennessee",
            "Arkansas",
            "Louisiana",
            "Oklahoma",
            "Texas",
        ],
    },
    {
        "region": "Midwest",
        "states": [
            "Illinois",
            "Indiana",
            "Michigan",
            "Ohio",
            "Wisconsin",
            "Iowa",
            "Kansas",
            "Minnesota",
            "Missouri",
            "Nebraska",
            "North Dakota",
            "South Dakota",
        ],
    },
    {
        "region": "West",
        "states": [
            "Arizona",
            "Colorado",
            "Idaho",
            "Montana",
            "Nevada",
            "New Mexico",
            "Utah",
            "Wyoming",
            "Alaska",
            "California",
            "Hawaii",
            "Oregon",
            "Washington",
        ],
    },
]
