<LandingPage>
    size_hint: 1, 1
    pos_hint: {'center_x': .5, 'center_y': .5}

    do_default_tab: False

    tab_pos: 'top_left'

    TabbedPanelItem:
        text: "Managers"
        

    TabbedPanelItem:
        text: "Campaigns"
       

    TabbedPanelItem:
        text: "Customers"
        

    TabbedPanelItem:
        text: "Enrollments"
        


    TabbedPanelItem:
        text: "Products"
        